services:
  model:
    image: "ghcr.io/remla23-team19/model-service:latest"
    ports:
      - "8080:8080"
  app:
    image: "ghcr.io/remla23-team19/app:latest"
    ports:
      - "9999:9999"
    environment:
      - MODEL_HOST=http://model:8080/sentiment
      - VERSION=latest
